apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: cluster-kc
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    database: postgresdb
    host: postgresql.default.svc
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    tlsSecret: keycloak-tls
  hostname:
    hostname: keycloak.blog.tremolo.dev
  ingress:
      enabled: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/secure-backends: 'true'
spec:
  rules:
  - host: keycloak.blog.tremolo.dev
    http:
      paths:
      - backend:
          service:
            name: cluster-kc-service
            port: 
              number: 8443
        path: "/"
        pathType: Prefix
  tls:
  - hosts:
    - keycloak.blog.tremolo.dev
    secretName: kc-tls-certificate-none